### ISSUE TITLE
Corrupted files?

### ISSUE THREAD

**Issue by noahcao** [yifeiyin04/Hi4D#5]
Hi, thanks for the good dataset!

When I tried to read certain files downloaded, the file can't be loaded by `np.load` with the error:

```
raise BadZipFile("File is not a zip file")
```

I downloaded the files from chrome. I list the files causing this issue here as I think they are probably corrupted:
```
pair19/piggyback19/seg/instance/0/mesh-f00088.npz 
pair00/dance00/seg/instance/0/mesh-f00149.npz 
pair32/fight32/seg/instance/1/mesh-f00117.npz
```

Could you help to check if they are in good shape on your side? Or, could you release a checksum file for the `*.tar.gz` files so that the users can quickly validate if the downloaded files are complete?

**Comment by MoyGcc** [comment]
Hi, thanks for your interest. And also thanks so much for pointing out the issues! I just quickly downloaded the zips and tested the files. It seems like both `pair19/piggyback19/seg/instance/0/mesh-f00088.npz` and `pair32/fight32/seg/instance/1/mesh-f00117.npz` are fine from my side and `pair00/dance00/seg/instance/0/mesh-f00149.npz` is indeed corrupted. I will work on this and come back to you asap (find the original files etc.). 

Sorry for the inconvenience!

**Comment by MoyGcc** [comment]
Hi, I found where the issue is. Our dataset server doesn't support large files (>16GB). I splitted `pair19` and `pair32` into two tar files and updated `pair00_1`. Could you please re-download these files? Hope that would fix the problems.
