### ISSUE TITLE
Conversion of Standard SMPL to Easymocap or Zju-mocap format

### ISSUE THREAD

**Issue by jinnan-chen** [yifeiyin04/Hi4D#7]
Hi, is there a converting function to convert the smpl data including global rotation and translation to Zju-mocap format including Rh and Th? Thanks! There is a documentation about this, but I am still not clear. https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md

**Comment by MoyGcc** [comment]
Hi, would [this](https://github.com/zju3dv/EasyMocap/blob/88c828e69ce9fc4c7a0d36ac7339d9e1ce200164/scripts/dataset/pre_hi4d.py) help? Easymocap authors tried to convert our format to their own.

**Comment by jinnan-chen** [comment]
Let me have a try, thanks~
