### ISSUE TITLE
Question about MVPose

### ISSUE THREAD

**Issue by CVStack** [yifeiyin04/Hi4D#8]
Thank you for sharing paper and dataset.

I am wondering how to obtain the SMPL parameter of HI4D for DMC.

I tried to run the MVPose code from below github repository but could get unconvincing results.
(https://github.com/openxrlab/xrmocap, https://github.com/zju3dv/EasyMocap)

Are there somethings to do before MVPose.

Thank you.

**Comment by MoyGcc** [comment]
Hi, thanks for your interest. We didn't do anything special for MVPose. Can you show some results of the poses? "Unconvincing" is a bit too abstract. The poses from MVPose we used in our experiment are also not perfect.

**Comment by CVStack** [comment]
Thank you for replying.

Here are some results from MVpose.

Good case   
![image](https://github.com/yifeiyin04/Hi4D/assets/38209962/7d41798a-db7d-4613-855d-e57859c28753)
![image](https://github.com/yifeiyin04/Hi4D/assets/38209962/54211207-5298-44db-a7fe-559f2e907644)

Bad case
![image](https://github.com/yifeiyin04/Hi4D/assets/38209962/b766544e-87c2-443d-98e1-036e5cf2c232)
![image](https://github.com/yifeiyin04/Hi4D/assets/38209962/db899852-81e5-40dc-804e-fa162914cee9)

Also, MVpose could not detect people for some samples, so we could not obtain smpl param of some samples.

Did you have the similar problem?
