### ISSUE TITLE
About downloading Hi4D

### ISSUE THREAD

**Issue by dqj5182** [yifeiyin04/Hi4D#9]
Could you provide downloading script for Hi4D dataset? I am unable to directly download the dataset with browser as I am downloading directly on server.

**Comment by MoyGcc** [comment]
Here is a script provided by other researchers: https://github.com/muelea/buddi/blob/main/documentation/DATA.md#hi4d. Could be useful.

**Comment by dqj5182** [comment]
Thank you for your quick response!
